<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>AutoHide</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TaleSpire" Version="1.6.0" />
    <PackageReference Include="Talespire.BepInEx" Version="5.4.22" />
    <PackageReference Include="TaleSpire.SetInjectionFlagPlugin" Version="3.4.1" />
  </ItemGroup>
</Project>
